Fix five broken JS files, and fail the build if they don't appear correctly in the combo's meta file.

diff --git a/buildout-templates/bin/combo-rootdir.in b/buildout-templates/bin/combo-rootdir.in
--- a/buildout-templates/bin/combo-rootdir.in
+++ b/buildout-templates/bin/combo-rootdir.in
@@ -19,3 +19,11 @@ utilities/js-deps -n LP_MODULES -s build/js/lp -o build/js/lp/meta.js >/dev/null
 #    outfile=$(echo $jsfile | sed -e 's/.js$/-min.js/')
 #	bin/py -m lp.scripts.utilities.js.jsmin < $jsfile > $outfile
 #done
+error=0
+for mod in $(grep '  LP' build/js/lp/meta.js | tr -s ' ' | cut -d\  -f2) ; do
+    if ! grep -q "modules\[$mod\]" build/js/lp/meta.js ; then
+        echo "ERROR: $mod is not mentioned in the meta file"
+        error=1
+    fi
+done
+exit $error
