Fix errant tabs in check-js-deps

diff --git a/utilities/check-js-deps b/utilities/check-js-deps
--- a/utilities/check-js-deps
+++ b/utilities/check-js-deps
@@ -7,10 +7,10 @@ set -e
 
 error=0
 for mod in $(grep '  LP' build/js/lp/meta.js | tr -s ' ' | cut -d\  -f2) ; do
-   	if ! grep -q "modules\[$mod\]" build/js/lp/meta.js ; then
-       	echo "ERROR: $mod is not mentioned in the meta file"
-       	error=1
-   	fi
+    if ! grep -q "modules\[$mod\]" build/js/lp/meta.js ; then
+        echo "ERROR: $mod is not mentioned in the meta file"
+        error=1
+    fi
 done
 exit $error
 
