add archive-mirror before launch Patches applied:
 * mark.shuttleworth@canonical.com/launchpad--devel--0--patch-840
   merge rocketfuel

 * mark.shuttleworth@canonical.com/launchpad--devel--0--patch-841
   merge rocketfuel

 * mark.shuttleworth@canonical.com/launchpad--devel--0--patch-842
   merge rocketfuel

 * mark.shuttleworth@canonical.com/launchpad--devel--0--patch-843
   add archive-mirror before pqm message in launch

diff --git a/utilities/launch b/utilities/launch
--- a/utilities/launch
+++ b/utilities/launch
@@ -56,5 +56,12 @@ if [ $? -gt 0 ]; then
   exit 1
 fi
 
+# mirror archive
+baz archive-mirror
+if [ $? -gt 0 ]; then
+  echo "Archive mirroring failed, cannot launch."
+  exit 1
+fi
+
 $LAUNCHPAD/arch-pqm/bin/arch-submit-merge "$1" pqm@pqm.ubuntu.com
 
