Corrected GPG key for bzr, add apache2 to installed packages, add lp:~launchpad ppa key.

diff --git a/utilities/rocketfuel-setup b/utilities/rocketfuel-setup
--- a/utilities/rocketfuel-setup
+++ b/utilities/rocketfuel-setup
@@ -256,14 +256,20 @@ if [ $? -ne 0 ]; then
   echo "deb http://lpdebs.canonical.com/${DISTRIB_CODENAME} ./" | sudo tee -a $LPDEV_SOURCES
 fi
 
+grep -q "^deb http://ppa.launchpad.net/launchpad/ppa/ubuntu intrepid/" $LPDEV_SOURCES
+if [ $? -ne 0 ]; then
+  echo "Adding LP package respository to package source list."
+  echo "deb http://ppa.launchpad.net/launchpad/ppa/ubuntu intrepid main"  | sudo tee -a $LPDEV_SOURCES
+fi
+
 grep -q "^deb http://ppa.launchpad.net/bzr/ubuntu" $LPDEV_SOURCES
 if [ $? -ne 0 ]; then
   echo "Adding Bazaar PPA repository to package source list."
-  echo "deb http://ppa.launchpad.net/bzr/ubuntu ${DISTRIB_CODENAME} main" | sudo tee -a $LPDEV_SOURCES
+  echo "deb http://ppa.launchpad.net/bzr/ppa/ubuntu ${DISTRIB_CODENAME} main" | sudo tee -a $LPDEV_SOURCES
 fi
 
 # Get the key used to sign the launchpad-developer-dependencies in the PPA.
-REQUIRED_PPA_KEYS="0A5174AF 2B97B7B8"
+REQUIRED_PPA_KEYS="0A5174AF 8C6C1EFD"
 for key in $REQUIRED_PPA_KEYS; do
    sudo apt-key list | grep -q $key
    if [ $? -ne 0 ]; then
@@ -281,19 +287,27 @@ for key in $REQUIRED_PPA_KEYS; do
    fi
 done
 
-sudo aptitude update
-dpkg -s launchpad-developer-dependencies | grep -q "^Status:.*installed"
-if [ $? -ne 0 ]; then
-  echo "Installing launchpad-developer-dependencies package..."
-  sudo aptitude install launchpad-developer-dependencies
+do_install() {
+  dpkg -s $pkg | grep -q "^Status:.*installed"
   if [ $? -ne 0 ]; then
-    echo "Unable to install LP developer dependencies"
-    exit 1
+    echo "Installing $pkg package..."
+    sudo aptitude install $pkg
+    if [ $? -ne 0 ]; then
+      echo "Unable to install $pkg."
+      exit 1
+    fi
   fi
-fi
+  }
 
-# Create the document root to avoid Apache warnings
+sudo aptitude update
+REQUIRED_PACKAGES="launchpad-developer-dependencies apache2"
+for pkg in $REQUIRED_PACKAGES; do
+  do_install;
+done
+
+# Create the document root(s) to avoid Apache warnings
 mkdir -p /var/tmp/bazaar.launchpad.dev/static
+mkdir -p /var/tmp/bazaar.launchpad.dev/mirrors
 
 # Create an empty rewritemap file so that Apache will start.
 mkdir -p /var/tmp/bazaar.launchpad.dev/config
@@ -512,7 +526,7 @@ committing changes to LP in utilities/rocketfuel-setup.
 Before you can submit branches to PQM, you need to visit:
 https://wiki.canonical.com/EmailSetup
 and find the current SMTP server password and enter it in the appropriate
-place in $HOME/.bazaar/locations.conf
+place in $HOME/.bazaar/locations.conf and $HOME/.bazaar/bazaar.conf.
 Alternatively, configure it to use your own SMTP server locally.
 
 You should use the following commands to manage your Rocketfuel:
@@ -532,7 +546,7 @@ You should use the following commands to manage your Rocketfuel:
     yet landed on trunk.
 
  rocketfuel-push
-    Push all of your branches to devpad, so that you have a server-side
+    Push all of your branches to Launchpad, so that you have a server-side
     backup of everything.
 
 Happy hacking!
